GET http://127.0.0.1:8000/api/clients
content-type: application/json


###


POST http://127.0.0.1:8000/api/clients
content-type: application/json

{
	"name": "Guacolda",
    "email": "guacolda@heyfoodie.cl"
}


###


GET http://127.0.0.1:8000/api/clients/5
content-type: application/json


###


PUT http://127.0.0.1:8000/api/clients/5
content-type: application/json

{
	"name": "Guacolda esposa de Lautaro",
    "email": "guacolda@heyfoodie.cl"
}


###


DELETE http://127.0.0.1:8000/api/clients/5
Content-Type: application/json