GET http://127.0.0.1:8000/api/ingredients
content-type: application/json


###


POST http://127.0.0.1:8000/api/ingredients
content-type: application/json

{
	"name": "Limon",
    "price": 1300,
	"stock": 20
}


###


GET http://127.0.0.1:8000/api/ingredients/11
content-type: application/json


###


PUT http://127.0.0.1:8000/api/ingredients/11
content-type: application/json

{
	"name": "Limón",
    "price": 1200,
	"stock": 30
}


###


DELETE http://127.0.0.1:8000/api/ingredients/11
Content-Type: application/json