@authToken = 1|nR9F9vVhQZpFeDz5POYKV9N414SNtbyBmXUjosmY

GET http://127.0.0.1:8000/api/potions
content-type: application/json
Authorization: Bearer {{authToken}}


###


POST http://127.0.0.1:8000/api/potions
content-type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Agua Para Resfrio",
	"ingredients": [{"ingredient_id": 7,"quantity": 0.3},{"ingredient_id": 8,"quantity": 0.1},{"ingredient_id": 9,"quantity": 0.4}]
}


###


GET http://127.0.0.1:8000/api/potions/4
content-type: application/json
Authorization: Bearer {{authToken}}


###


PUT http://127.0.0.1:8000/api/potions/4
content-type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Agua Para Resfrio",
	"ingredients": [{"ingredient_id": 7,"quantity": 0.3},{"ingredient_id": 8,"quantity": 0.1}]
}


###


DELETE http://127.0.0.1:8000/api/potions/1
Content-Type: application/json
Authorization: Bearer {{authToken}}
